.TH repodude 1
.SH NAME
.B repodude
\- a package database creator
.SH SYNOPSIS
.B repodude
CSV DATABASE
.SH DESCRIPTION
Converts a
.B
CSV
file into a
.B packdude(8)
package database, suitable for use for a repository.

Typically, a
.B repodude
input file contains lines in the format
.B package,version,description,file_name,architecture,dependencies
, while the dependencies list is a space-delimeted string which specifies
dependency package names.
.SH "SEE ALSO"
.B dudepack(1), packdude(8)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)
