#ifndef _ERROR_H_INCLUDED
#	define _ERROR_H_INCLUDED

typedef unsigned int result_t;

enum result_types {
	/* generic */
	RESULT_OK,
	RESULT_GENERIC_ERROR,
	RESULT_MALLOC_FAILED,

	/* metadata.c */
	RESULT_NO_LINE_BREAK,
	RESULT_NO_SEPARATOR,
	RESULT_FPRINTF_FAILED,

	/* package.c */
	RESULT_FILE_MISSING,
	RESULT_MMAP_FAILED,
	RESULT_INVALID_SIZE,
	RESULT_NO_ARCHITECURE,
	RESULT_INCOMPATIBLE_ARCHITECURE,
	RESULT_BAD_CHECKSUM,

	/* archive.c */
	RESULT_READ_BLOCK_FAILED,
	RESULT_WRITE_BLOCK_FAILED,
	RESULT_ARCHIVE_READ_NEW_FAILED,
	RESULT_ARCHIVE_WRITE_DISK_NEW_FAILED,
	RESULT_ARCHIVE_READ_OPEN_MEMORY_FAILED,
	RESULT_GETCWD_FAILED,
	RESULT_CHDIR_FAILED,
	RESULT_READ_NEXT_HEADER_FAILED,
	RESULT_WRITE_HEADER_FAILED,

	/* fetch.c */
	RESULT_EASY_INIT_FAILED,
	RESULT_EASY_SETOPT_FAILED,
	RESULT_EASY_PERFORM_FAILED,

	/* database.c, metadata.c */
	RESULT_FOPEN_FAILED,

	/* manager.c */
	RESULT_ALREADY_INSTALLED,

	/* package.c */
	RESULT_NO_DEPENDENCIES_FIELD,
	RESULT_INVALID_DEPENDENCIES,
	RESULT_STRDUP_FAILED,
	RESULT_YES,
	RESULT_NO,
	RESULT_NO_NAME_FIELD
};

#endif
